data_url = "https://stats.nba.com/stats/leaguedashteamstats?Conference=&DateFrom=10%2F01%2F{2}&DateTo={0}%2F{1}%2F{3}&Division=&GameScope=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season={4}&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision="

[get-data.2023-24]
start_date = "2023-10-23"
end_date   = "2024-04-28"
start_year = "2023"
end_year   = "2024"

[get-data.2024-25]
start_date = "2024-10-21"
end_date   = "2025-06-20"
start_year = "2024"
end_year   = "2025"

[get-data.2025-26]
start_date = "2025-10-20"
end_date   = "2025-11-08"
start_year = "2025"
end_year   = "2026"

[get-odds-data.2023-24]
start_date = "2023-10-23"
end_date   = "2024-04-28"
start_year = "2023"
end_year   = "2024"

[get-odds-data.2024-25]
start_date = "2024-10-21"
end_date   = "2025-06-20"
start_year = "2024"
end_year   = "2025"

[get-odds-data.2025-26]
start_date = "2025-10-20"
end_date   = "2025-11-08"
start_year = "2025"
end_year   = "2026"

[create-games.2023-24]
start_date = "2023-10-23"
end_date   = "2024-04-28"
start_year = "2023"
end_year   = "2024"

[create-games.2024-25]
start_date = "2024-10-21"
end_date   = "2025-06-20"
start_year = "2024"
end_year   = "2025"

[create-games.2025-26]
start_date = "2025-10-20"
end_date   = "2025-11-08"
start_year = "2025"
end_year   = "2026"
